### ISSUE TITLE
Requesting your approval to include rpId in MAC and private key derivations?

### ISSUE THREAD

**Issue by UppaJung** [dicekeys/seeding-webauthn#2]
@nickray:

This issue exists to make sure you are aware of the `rpId` field in to the calculation of `credentialMac` and `es256SPrivateKey`.

You had previously documented that you didn't use `rpId` in those situations since it is not available within the `credentialId`, but it will still be available when we need it since it is a parameter toto [authenticatorGetAssertion](https://www.w3.org/TR/webauthn/#op-get-assertion))

**Comment by nickray** [comment]
Ah yes, correct. We should treat it like "associated data" in the MAC tag.

**Comment by UppaJung** [comment]
OK.  Close if you consider resolved.
