### ISSUE TITLE
Does secret key derivation require modular reduction?

### ISSUE THREAD

**Issue by UppaJung** [dicekeys/seeding-webauthn#4]
@nickray

Do we need a modular reduction operation as part of the derivation of the secret key?

**Comment by nickray** [comment]
Yes, we need to specify whether we interpret as little vs big endian, whether we do modular reduction also if seed > prime or rejection sampling in that case to avoid bias (and how to iterate if so, e. g. hmac again or what).

Perhaps ideally we supply a Python routine and some test vectors to lock down seed->private key transformation?

**Comment by UppaJung** [comment]
@nicray Proposed
AFAIK there is no "generally shared" map: 32 bytes (privateKeySeed) -> P256 private key. If there is some RFC, let's use that, if not, we have to specify one. One procedure I could think of ("rejection sampling with iterated hashing", but this we should ask a cryptographer about) is:

interpret the 32 bytes as little-endian integer S between 0 and 2^256 - 1
if 1 <= S < order of the P256 group, use S to set private key = S * canonical generator (multiplication as Z-module)
if not, set S = SHA256(S), and goto 1.

**Comment by nickray** [comment]
https://colab.research.google.com/drive/1liWfrX5J04pWqHo-cGIu0NZYrsUH51CT#scrollTo=LbxjFbNFj3oL&line=2

**Comment by UppaJung** [comment]
See https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-4.pdf B.4.2

**Comment by nickray** [comment]
https://datatracker.ietf.org/doc/draft-irtf-cfrg-hash-to-curve/

**Comment by UppaJung** [comment]
Good find.  Are you proposing we use that over NIST?

**Comment by UppaJung** [comment]
Joe said stick with NIST
