### ISSUE TITLE
Discuss if AAGUID needs to be in spec

### ISSUE THREAD

**Issue by UppaJung** [dicekeys/seeding-webauthn#6]
Nicolas asks "Choice of shared AAGUID: should just pick one and add to the spec"
    Stuart asks: since the AAGUID is not an input to any of the operations, does the spec need to specify an AAGUID?

**Comment by nickray** [comment]
- AAGUID is used during MC (makeCredential) operation: before this is even called, during GI (getInfo, self-identification of authenticator), authenticator states its AAGUID. This is eventually passed on to RP, which can a) lookup "metadata about the authenticator implementation" via AAGUID in some way (FIDO Alliance MDS, or well-known, or whitelisted), and b) check the attestation for the generated credential uses the private attestation key expected for the authenticator / AAGUID

- AAGUID is not used (or at least highly optional) during GA (getAssertion), i.e. log-in:  Essentially, the credential key is used to sign `clientData || authenticatorData`, where the random challenge is in client and the AAGUID is not in authenticator data (https://www.w3.org/TR/webauthn/#authenticator-data).

So I think it might make sense to define an AAGUID to signal "credentials generated using our spec" (although this would just give RPs the opportunity to blacklist us), but an authenticator implementation could also pick its own.

cc @conorpp

**Comment by nickray** [comment]
So the answer is no.
